#Misc information
site_name: Laurent Dumont - Internet notepad.
site_description: 'My own little space'
site_author: 'Laurent Dumont'
google_analytics: ['UA-51757315-3', 'auto']

#Page list
nav:
      - Home: index.md
      - AWS: aws-cli.md
      - Chef: chef.md
      - Cisco-CCNA: ccna.md
      - Cisco: cisco.md
      - Cumulus: cumulus.md
      - Docker: docker.md
      - Elasticsearch: elasticsearch.md
      - Foreman: foreman.md
      - Generic Linux: linux.md
      - Git: git.md
      - Gluster: gluster.md
      - iPerf: iperf.md
      - ISCSI: iscsi.md
      - Juniper: juniper.md
      - Kolla: kolla.md
      - Kubernetes: kubernetes.md
      - KVM: kvm.md
      - LVM: lvm.md
      - Metasploit: metasploit.md
      - MAAS: maas.md
      - Molecule: molecule.md
      - MySQL/MariaDB: mysql.md
      - Netbox: netbox.md
      - Openstack: openstack.md
      - OPNFV: opnfv.md
      - OVS: ovs.md
      - Pentesting: pentest.md
      - Postgres: postgres.md
      - Prometheus: prometheus.md
      - Proxmox: proxmox.md
      - Python: python.md
      - Security: security.md
      - Splunk: splunk.md
      - Tripleo: tripleo.md
      - Terraform: terraform.md
      - FRR: frr.md
      - Wireshark: wireshark.md
      - Bluetooth: bluetooth.md
      - RaspPi: rasppi.md

    
#Theme customization
theme:
      name: 'material'
      palette:
        primary: 'grey'
        scheme: slate
      icon:
        logo: material/cloud
      favicon: 'images/tarsier_hi_elbows.ico'

# Repository
repo_name: 'ns-cheatsheet'
repo_url: 'https://github.com/LaurentDumont/ns-cheatsheet'

# Copyright
copyright: 'Copyright &copy; Potato Tomato - Send me bitcoins - Laurent Dumont'

#Enabled extensions
markdown_extensions:
      - codehilite

#Media Footer
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: 'https://github.com/laurentdumont'
      - icon: fontawesome/brands/linkedin
        link: 'https://www.linkedin.com/in/laurentfdumont/'

extra_css:
  - css/extra.css
