site_name: My own little internet Notepad.
site_description: 'My own little space'
site_author: 'Laurent Dumont'

pages:
      - Home: index.md
      - Cisco: cisco.md
      - Linux: linux.md

theme:
      name: 'material'
      palette:
        primary: 'grey'
      logo:
        icon: 'cloud circle'
      favicon: 'images/tarsier_hi_elbows.ico'

# Repository
repo_name: 'squidfunk/mkdocs-material'
repo_url: 'https://github.com/squidfunk/mkdocs-material'

# Copyright
copyright: 'Copyright &copy; Potato Tomato - Send my bitcoins - Laurent Dumont'

markdown_extensions:
      - codehilite
extra:
    social:
      - type: 'github'
        link: 'https://github.com/laurentdumont'
      - type: 'linkedin'
        link: 'https://www.linkedin.com/in/laurentfdumont/'
