#Misc information
site_name: Laurent Dumont - Internet notepad.
site_description: 'My own little space'
site_author: 'Laurent Dumont'
google_analytics: ['UA-51757315-3', 'auto']

#Page list
nav:
      - Home: index.md
      - Cisco: cisco.md
      - Cisco-CCNA: ccna.md
      - Generic Linux: linux.md
      - Gluster: gluster.md
      - Prometheus: prometheus.md
      - iPerf: iperf.md
      - Juniper: juniper.md
      - Netbox: netbox.md
      - Splunk: splunk.md
      - Chef: chef.md
      - Openstack: openstack.md
      - Docker: docker.md
      - Molecule: molecule.md
      - Git: git.md
      - MAAS: maas.md
      - Postgres: postgres.md
      - MySQL/MariaDB: mysql.md
      - LVM: lvm.md
      - Security: security.md
      - Foreman: foreman.md
      - OVS: ovs.md
      - Terraform: terraform.md
      - Kolla: kolla.md

    
#Theme customization
theme:
      name: 'material'
      palette:
        primary: 'grey'
      logo:
        icon: 'cloud circle'
      favicon: 'images/tarsier_hi_elbows.ico'

# Repository
repo_name: 'ns-cheatsheet'
repo_url: 'https://github.com/LaurentDumont/ns-cheatsheet'

# Copyright
copyright: 'Copyright &copy; Potato Tomato - Send me bitcoins - Laurent Dumont'

#Enabled extensions
markdown_extensions:
      - codehilite

#Media Footer
extra:
    social:
      - type: 'github'
        link: 'https://github.com/laurentdumont'
      - type: 'linkedin'
        link: 'https://www.linkedin.com/in/laurentfdumont/'
